//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House_Project2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Categorie { get; set; }
        public int HouseType { get; set; }
        public int Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual HouseType HouseType1 { get; set; }

    }
}
